# Generated by Django 3.0.8 on 2020-07-28 18:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogpost',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=20)),
                ('head0', models.CharField(default='', max_length=500)),
                ('chead0', models.CharField(default='', max_length=5000)),
                ('head2', models.CharField(default='', max_length=500)),
                ('chaed2', models.CharField(default='', max_length=5000)),
                ('pub_date', models.DateField(blank=True, default=datetime.datetime.now)),
                ('author', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
