# Generated by Django 3.0.8 on 2020-07-29 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='thumbnail',
            field=models.ImageField(default='', upload_to='iblog/media'),
        ),
    ]
