# Generated by Django 3.0.8 on 2020-07-29 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iblog', '0002_blogpost_thumbnail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='chaed2',
            new_name='chead1',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='chead2',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='head1',
            field=models.CharField(default='', max_length=500),
        ),
    ]
